---
spring:
  resources.static-locations: "file:./app"
cds:
  odata-v4.endpoint.path: "/api"
  services:
    abp:
      name: API_BUSINESS_PARTNER
      messaging:
        type: "s4hana"
        topic-namespace: "sap/S4HANAOD/dkom"
  security.mock.users:
    - name: admin
      password: admin
      roles:
      - admin
      attributes:
        businessPartner:
        - SAPSE
    - name: user
      password: user

---
spring:
  profiles: cloud
cds:
  services:
    abp:
      serve:
        ignore: true
      destination: "s4-business-partner-api"
---
spring:
  profiles: sqlite
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1
